apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
  namespace: messages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: peervetzler/sendandreceivemessages:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
