apiVersion: v1
kind: Service
metadata:
  name: receiver-service
  namespace: messages
spec:
  selector:
    app: receiver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
